### PR TITLE
OAuth2 credentials

### PR DESCRIPTION
**Pull request by martinlehoux**
Enable authentication through OAuth2 protocol

### CODE REVIEW

**Comment by dkarchmer** [comment]
@martinlehoux did you talk to filippo? I didn't know we were using this package for the new app. I would have expected we would modify https://github.com/iotile/ng-arch-common

**Comment by martinlehoux** [comment]
I didn't know there was a new repo : most of app.archfx.io code uses this one : https://github.com/iotile/app.archfx.io/blob/1c7781903843eb47cd20f089c624b5c7042d8614/src/app/auth/components/login-form/login-form.component.ts#L6
But if we are in the process to moving to the new one, I can do it there

**Comment by dkarchmer** [comment]
This repo  has not even changed for a long time, so I am surprised we use it for anything.

@fil-forti is the one that needs to approve this, as he should know if this is the right place to change

Do note that this package for sure is used by app.iotile.cloud so we need to be sure nothing breaks there

**Comment by fil-forti** [comment]
Yes, this package is really old, but it's still used by the webapp for login and some other API calls. It would be a good idea to create a new package that handles everything because now some code is here and some in the webapp. But I think for now we can just add this change here and come up with the new package later. 
The code looks good to me, and I only see additions to the code it shouldn't be backward compatible with app.iotile.cloud

**Comment by fil-forti** [comment]
Over the weekend I thought it would be a better idea to ignore this package and just add the code to the app directly. I think it would make things easier for everyone. On the ArchFX webapp repo, I created a [new branch](https://github.com/iotile/app.archfx.io/tree/oauth2) you can work on, I simply created a new service so you can just paste the code you already wrote in there and keep working on the Oauth2 login feature

**Pull request closed without merging**
